name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - "packages/container/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configurar registro de NPM
        run: npm config set registry https://registry.npmjs.org

      - name: Instalar dependencias
        run: npm install

      - name: Compilar proyecto
        run: npm run build

      - name: Instalar AWS CLI
        uses: shinyinc/action-aws-cli@v1.2

      - name: Verificar valor del bucket
        run: |
          if [ -z "${{ secrets.AWS_S3_BUCKET_NAME }}" ]; then
            echo "❌ El secreto AWS_S3_BUCKET_NAME está vacío"
            exit 1
          else
            echo "✅ Bucket ${{ secrets.AWS_S3_BUCKET_NAME }}"
          fi

      - name: Subir a S3
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - run: aws cloudfront creative-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID}} --paths "/container/latest/index.html"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
